// DB type: relational (PostgreSQL)
// Replication:
// - master-slave (async)
// - replication factor 3
//
// Sharding:
// - key based by post_id

Table comments {
  id uuid [primary key]
  post_id uuid
  reply_to uuid
  author_id uuid
  text text
  created_at timestamp
}