// DB type: relational (PostgreSQL)
// Replication:
// - master-slave (async)
// - replication factor 3

Table locations {
  id uuid [primary key]
  name varchar
  description text
  latitude float
  longitude float
  created_at timestamp
}