// DB type: relational (PostgreSQL)
// Replication:
// - master-slave (async)
// - replication factor 3
//
// Sharding:
// - key based by author_id

Table posts {
  id uuid [primary key]
  author_id uuid
  location_id uuid
  text text [note: 'Content of the post']
  created_at timestamp
}

// Sharding:
// - key based by post_id

Table photos {
  id uuid [primary key]
  post_id uuid
  url varchar
  created_at timestamp
}

