// DB type: relational (PostgreSQL)
// Replication:
// - master-slave (async)
// - replication factor 3
//
// Sharding:
// - key based by post_id

Table reactions {
  id uuid [primary key]
  post_id uuid
  author_id uuid
  type integer
  created_at timestamp
}