// DB type: relational (PostgreSQL)
// Replication:
// - master-slave (async)
// - replication factor 3
//
// Sharding:
// - key based by id

Table users {
  id uuid [primary key]
  name varchar
  gender varchar
  date_of_birth date
  created_at timestamp
}

Table follows {
  following_user_id integer
  followed_user_id integer
  created_at timestamp
}